package pqt.dss.ptrf.model.eo;

import java.sql.SQLException;

import javax.faces.context.ExternalContext;
import javax.faces.context.FacesContext;

import javax.servlet.http.HttpSession;

import oracle.jbo.AttributeList;
import oracle.jbo.Key;
import oracle.jbo.RowIterator;
import oracle.jbo.domain.Date;
import oracle.jbo.domain.Number;
import oracle.jbo.server.EntityDefImpl;
import oracle.jbo.server.EntityImpl;
import oracle.jbo.server.SequenceImpl;
import oracle.jbo.server.TransactionEvent;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Mon Jan 08 12:36:57 PKT 2018
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class DssPlanTransferLinesImpl extends EntityImpl {
    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. DO NOT MODIFY.
     */
    public enum AttributesEnum {
        TrLineIdPk,
        TrHeaderIdFk,
        UserIdFk,
        EnterDate,
        LastUpdatedBy,
        LastUpdatedDate,
        ToAgentNoFk,
        BranchCodeFk,
        ToPersisSec,
        ToPersisThrd,
        ToQuaterlyBusPol,
        ToQuaterlyBus,
        ToHalfYearlyBusPol,
        ToHalfYearlyBus,
        ToYearlyBusPol,
        ToYearlyBus,
        ToAgentPortfolio,
        FromAgentNoFk,
        DssPlanTransferHeader,
        DssPlanTransferLineDetails;
        private static AttributesEnum[] vals = null;
        private static final int firstIndex = 0;

        public int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        public static final int firstIndex() {
            return firstIndex;
        }

        public static int count() {
            return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
        }

        public static final AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }
    public static final int TRLINEIDPK = AttributesEnum.TrLineIdPk.index();
    public static final int TRHEADERIDFK = AttributesEnum.TrHeaderIdFk.index();
    public static final int USERIDFK = AttributesEnum.UserIdFk.index();
    public static final int ENTERDATE = AttributesEnum.EnterDate.index();
    public static final int LASTUPDATEDBY = AttributesEnum.LastUpdatedBy.index();
    public static final int LASTUPDATEDDATE = AttributesEnum.LastUpdatedDate.index();
    public static final int TOAGENTNOFK = AttributesEnum.ToAgentNoFk.index();
    public static final int BRANCHCODEFK = AttributesEnum.BranchCodeFk.index();
    public static final int TOPERSISSEC = AttributesEnum.ToPersisSec.index();
    public static final int TOPERSISTHRD = AttributesEnum.ToPersisThrd.index();
    public static final int TOQUATERLYBUSPOL = AttributesEnum.ToQuaterlyBusPol.index();
    public static final int TOQUATERLYBUS = AttributesEnum.ToQuaterlyBus.index();
    public static final int TOHALFYEARLYBUSPOL = AttributesEnum.ToHalfYearlyBusPol.index();
    public static final int TOHALFYEARLYBUS = AttributesEnum.ToHalfYearlyBus.index();
    public static final int TOYEARLYBUSPOL = AttributesEnum.ToYearlyBusPol.index();
    public static final int TOYEARLYBUS = AttributesEnum.ToYearlyBus.index();
    public static final int TOAGENTPORTFOLIO = AttributesEnum.ToAgentPortfolio.index();
    public static final int FROMAGENTNOFK = AttributesEnum.FromAgentNoFk.index();
    public static final int DSSPLANTRANSFERHEADER = AttributesEnum.DssPlanTransferHeader.index();
    public static final int DSSPLANTRANSFERLINEDETAILS = AttributesEnum.DssPlanTransferLineDetails.index();

    /**
     * This is the default constructor (do not remove).
     */
    public DssPlanTransferLinesImpl() {
    }

    /**
     * Gets the attribute value for TrLineIdPk, using the alias name TrLineIdPk.
     * @return the value of TrLineIdPk
     */
    public Number getTrLineIdPk() {
        return (Number) getAttributeInternal(TRLINEIDPK);
    }

    /**
     * Sets <code>value</code> as the attribute value for TrLineIdPk.
     * @param value value to set the TrLineIdPk
     */
    public void setTrLineIdPk(Number value) {
        setAttributeInternal(TRLINEIDPK, value);
    }

    /**
     * Gets the attribute value for TrHeaderIdFk, using the alias name TrHeaderIdFk.
     * @return the value of TrHeaderIdFk
     */
    public Number getTrHeaderIdFk() {
        return (Number) getAttributeInternal(TRHEADERIDFK);
    }

    /**
     * Sets <code>value</code> as the attribute value for TrHeaderIdFk.
     * @param value value to set the TrHeaderIdFk
     */
    public void setTrHeaderIdFk(Number value) {
        setAttributeInternal(TRHEADERIDFK, value);
    }

    /**
     * Gets the attribute value for UserIdFk, using the alias name UserIdFk.
     * @return the value of UserIdFk
     */
    public Number getUserIdFk() {
        return (Number) getAttributeInternal(USERIDFK);
    }

    /**
     * Sets <code>value</code> as the attribute value for UserIdFk.
     * @param value value to set the UserIdFk
     */
    public void setUserIdFk(Number value) {
        setAttributeInternal(USERIDFK, value);
    }

    /**
     * Gets the attribute value for EnterDate, using the alias name EnterDate.
     * @return the value of EnterDate
     */
    public Date getEnterDate() {
        return (Date) getAttributeInternal(ENTERDATE);
    }

    /**
     * Sets <code>value</code> as the attribute value for EnterDate.
     * @param value value to set the EnterDate
     */
    public void setEnterDate(Date value) {
        setAttributeInternal(ENTERDATE, value);
    }

    /**
     * Gets the attribute value for LastUpdatedBy, using the alias name LastUpdatedBy.
     * @return the value of LastUpdatedBy
     */
    public Number getLastUpdatedBy() {
        return (Number) getAttributeInternal(LASTUPDATEDBY);
    }

    /**
     * Sets <code>value</code> as the attribute value for LastUpdatedBy.
     * @param value value to set the LastUpdatedBy
     */
    public void setLastUpdatedBy(Number value) {
        setAttributeInternal(LASTUPDATEDBY, value);
    }

    /**
     * Gets the attribute value for LastUpdatedDate, using the alias name LastUpdatedDate.
     * @return the value of LastUpdatedDate
     */
    public Date getLastUpdatedDate() {
        return (Date) getAttributeInternal(LASTUPDATEDDATE);
    }

    /**
     * Sets <code>value</code> as the attribute value for LastUpdatedDate.
     * @param value value to set the LastUpdatedDate
     */
    public void setLastUpdatedDate(Date value) {
        setAttributeInternal(LASTUPDATEDDATE, value);
    }

    /**
     * Gets the attribute value for ToAgentNoFk, using the alias name ToAgentNoFk.
     * @return the value of ToAgentNoFk
     */
    public Number getToAgentNoFk() {
        return (Number) getAttributeInternal(TOAGENTNOFK);
    }

    /**
     * Sets <code>value</code> as the attribute value for ToAgentNoFk.
     * @param value value to set the ToAgentNoFk
     */
    public void setToAgentNoFk(Number value) {
        setAttributeInternal(TOAGENTNOFK, value);
    }

    /**
     * Gets the attribute value for BranchCodeFk, using the alias name BranchCodeFk.
     * @return the value of BranchCodeFk
     */
    public String getBranchCodeFk() {
        return (String) getAttributeInternal(BRANCHCODEFK);
    }

    /**
     * Sets <code>value</code> as the attribute value for BranchCodeFk.
     * @param value value to set the BranchCodeFk
     */
    public void setBranchCodeFk(String value) {
        setAttributeInternal(BRANCHCODEFK, value);
    }

    /**
     * Gets the attribute value for ToPersisSec, using the alias name ToPersisSec.
     * @return the value of ToPersisSec
     */
    public Number getToPersisSec() {
        return (Number) getAttributeInternal(TOPERSISSEC);
    }

    /**
     * Sets <code>value</code> as the attribute value for ToPersisSec.
     * @param value value to set the ToPersisSec
     */
    public void setToPersisSec(Number value) {
        setAttributeInternal(TOPERSISSEC, value);
    }

    /**
     * Gets the attribute value for ToPersisThrd, using the alias name ToPersisThrd.
     * @return the value of ToPersisThrd
     */
    public Number getToPersisThrd() {
        return (Number) getAttributeInternal(TOPERSISTHRD);
    }

    /**
     * Sets <code>value</code> as the attribute value for ToPersisThrd.
     * @param value value to set the ToPersisThrd
     */
    public void setToPersisThrd(Number value) {
        setAttributeInternal(TOPERSISTHRD, value);
    }

    /**
     * Gets the attribute value for ToQuaterlyBusPol, using the alias name ToQuaterlyBusPol.
     * @return the value of ToQuaterlyBusPol
     */
    public Number getToQuaterlyBusPol() {
        return (Number) getAttributeInternal(TOQUATERLYBUSPOL);
    }

    /**
     * Sets <code>value</code> as the attribute value for ToQuaterlyBusPol.
     * @param value value to set the ToQuaterlyBusPol
     */
    public void setToQuaterlyBusPol(Number value) {
        setAttributeInternal(TOQUATERLYBUSPOL, value);
    }

    /**
     * Gets the attribute value for ToQuaterlyBus, using the alias name ToQuaterlyBus.
     * @return the value of ToQuaterlyBus
     */
    public Number getToQuaterlyBus() {
        return (Number) getAttributeInternal(TOQUATERLYBUS);
    }

    /**
     * Sets <code>value</code> as the attribute value for ToQuaterlyBus.
     * @param value value to set the ToQuaterlyBus
     */
    public void setToQuaterlyBus(Number value) {
        setAttributeInternal(TOQUATERLYBUS, value);
    }

    /**
     * Gets the attribute value for ToHalfYearlyBusPol, using the alias name ToHalfYearlyBusPol.
     * @return the value of ToHalfYearlyBusPol
     */
    public Number getToHalfYearlyBusPol() {
        return (Number) getAttributeInternal(TOHALFYEARLYBUSPOL);
    }

    /**
     * Sets <code>value</code> as the attribute value for ToHalfYearlyBusPol.
     * @param value value to set the ToHalfYearlyBusPol
     */
    public void setToHalfYearlyBusPol(Number value) {
        setAttributeInternal(TOHALFYEARLYBUSPOL, value);
    }

    /**
     * Gets the attribute value for ToHalfYearlyBus, using the alias name ToHalfYearlyBus.
     * @return the value of ToHalfYearlyBus
     */
    public Number getToHalfYearlyBus() {
        return (Number) getAttributeInternal(TOHALFYEARLYBUS);
    }

    /**
     * Sets <code>value</code> as the attribute value for ToHalfYearlyBus.
     * @param value value to set the ToHalfYearlyBus
     */
    public void setToHalfYearlyBus(Number value) {
        setAttributeInternal(TOHALFYEARLYBUS, value);
    }

    /**
     * Gets the attribute value for ToYearlyBusPol, using the alias name ToYearlyBusPol.
     * @return the value of ToYearlyBusPol
     */
    public Number getToYearlyBusPol() {
        return (Number) getAttributeInternal(TOYEARLYBUSPOL);
    }

    /**
     * Sets <code>value</code> as the attribute value for ToYearlyBusPol.
     * @param value value to set the ToYearlyBusPol
     */
    public void setToYearlyBusPol(Number value) {
        setAttributeInternal(TOYEARLYBUSPOL, value);
    }

    /**
     * Gets the attribute value for ToYearlyBus, using the alias name ToYearlyBus.
     * @return the value of ToYearlyBus
     */
    public Number getToYearlyBus() {
        return (Number) getAttributeInternal(TOYEARLYBUS);
    }

    /**
     * Sets <code>value</code> as the attribute value for ToYearlyBus.
     * @param value value to set the ToYearlyBus
     */
    public void setToYearlyBus(Number value) {
        setAttributeInternal(TOYEARLYBUS, value);
    }

    /**
     * Gets the attribute value for ToAgentPortfolio, using the alias name ToAgentPortfolio.
     * @return the value of ToAgentPortfolio
     */
    public Number getToAgentPortfolio() {
        return (Number) getAttributeInternal(TOAGENTPORTFOLIO);
    }

    /**
     * Sets <code>value</code> as the attribute value for ToAgentPortfolio.
     * @param value value to set the ToAgentPortfolio
     */
    public void setToAgentPortfolio(Number value) {
        setAttributeInternal(TOAGENTPORTFOLIO, value);
    }

    /**
     * Gets the attribute value for FromAgentNoFk, using the alias name FromAgentNoFk.
     * @return the value of FromAgentNoFk
     */
    public Number getFromAgentNoFk() {
        return (Number) getAttributeInternal(FROMAGENTNOFK);
    }

    /**
     * Sets <code>value</code> as the attribute value for FromAgentNoFk.
     * @param value value to set the FromAgentNoFk
     */
    public void setFromAgentNoFk(Number value) {
        setAttributeInternal(FROMAGENTNOFK, value);
    }

    /**
     * @return the associated entity DssPlanTransferHeaderImpl.
     */
    public DssPlanTransferHeaderImpl getDssPlanTransferHeader() {
        return (DssPlanTransferHeaderImpl) getAttributeInternal(DSSPLANTRANSFERHEADER);
    }

    /**
     * Sets <code>value</code> as the associated entity DssPlanTransferHeaderImpl.
     */
    public void setDssPlanTransferHeader(DssPlanTransferHeaderImpl value) {
        setAttributeInternal(DSSPLANTRANSFERHEADER, value);
    }

    /**
     * @return the associated entity oracle.jbo.RowIterator.
     */
    public RowIterator getDssPlanTransferLineDetails() {
        return (RowIterator) getAttributeInternal(DSSPLANTRANSFERLINEDETAILS);
    }

    /**
     * @param trLineIdPk key constituent

     * @return a Key object based on given key constituents.
     */
    public static Key createPrimaryKey(Number trLineIdPk) {
        return new Key(new Object[] { trLineIdPk });
    }

    /**
     * @return the definition object for this instance class.
     */
    public static synchronized EntityDefImpl getDefinitionObject() {
        return EntityDefImpl.findDefObject("pqt.dss.ptrf.model.eo.DssPlanTransferLines");
    }

    /**
     * Add attribute defaulting logic in this method.
     * @param attributeList list of attribute names/values to initialize the row
     */
     protected void create(AttributeList attributeList) {
      super.create(attributeList);
      Date currentDate = new Date();
      setEnterDate((Date) currentDate.getCurrentDate());
      setLastUpdatedDate((Date) currentDate.getCurrentDate());
      SequenceImpl seq = new SequenceImpl("DSS_PLAN_TRANSFER_LINES_SEQ", getDBTransaction());
      setTrLineIdPk(seq.getSequenceNumber());
      
    //         setBranchStatus("INCOMPLETE");
    //         setDssStatus("INCOMPLETE");
      
      FacesContext fctx = FacesContext.getCurrentInstance();
      ExternalContext ectx = fctx.getExternalContext();
      HttpSession userSession = (HttpSession) ectx.getSession(false);
      try {
          setUserIdFk(new Number(userSession.getAttribute("pUserId")));
          setLastUpdatedBy(new Number(userSession.getAttribute("pUserId")));
      } catch (SQLException ex) {
          setUserIdFk(new Number(0));
          setLastUpdatedBy(new Number(0));
      }
     }

    /**
     * Add entity remove logic in this method.
     */
    public void remove() {
        super.remove();
    }

    /**
     * Add locking logic here.
     */
    public void lock() {
        super.lock();
    }

    /**
         * Custom DML update/insert/delete logic here.
         * @param operation the operation type
         * @param e the transaction event
         */
        protected void doDML(int operation, TransactionEvent e) {
            Date currentDate = new Date();
            if (operation == DML_UPDATE) {
                setLastUpdatedDate((Date) currentDate.getCurrentDate());
                FacesContext fctx = FacesContext.getCurrentInstance();
                ExternalContext ectx = fctx.getExternalContext();
                HttpSession userSession = (HttpSession) ectx.getSession(false);
                try {
                    setUserIdFk(new Number(userSession.getAttribute("pUserId")));
//                    setLastUpdatedBy(new Number(userSession.getAttribute("pUserId")));
                } catch (SQLException ex) {
                    setUserIdFk(new Number(0));
//                    setLastUpdatedBy(new Number(0));
                }
            }
            super.doDML(operation, e);
        }
}

