package pqt.dss.ptrf.model.vo.psr;

import javax.faces.context.ExternalContext;
import javax.faces.context.FacesContext;

import javax.servlet.http.HttpSession;

import oracle.jbo.domain.Date;
import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Thu Sep 30 11:01:22 PKT 2021
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class DssPtPsrCommentsHeaderQVOImpl extends ViewObjectImpl {
    /**
     * This is the default constructor (do not remove).
     */
    public DssPtPsrCommentsHeaderQVOImpl() {
    }

    /**
     * Returns the variable value for VC_FROM_DATE.
     * @return variable value for VC_FROM_DATE
     */
    public Date getVC_FROM_DATE() {
        return (Date) ensureVariableManager().getVariableValue("VC_FROM_DATE");
    }

    /**
     * Sets <code>value</code> for variable VC_FROM_DATE.
     * @param value value to bind as VC_FROM_DATE
     */
    public void setVC_FROM_DATE(Date value) {
        ensureVariableManager().setVariableValue("VC_FROM_DATE", value);
    }

    /**
     * Returns the variable value for VC_TO_DATE.
     * @return variable value for VC_TO_DATE
     */
    public Date getVC_TO_DATE() {
        return (Date) ensureVariableManager().getVariableValue("VC_TO_DATE");
    }

    /**
     * Sets <code>value</code> for variable VC_TO_DATE.
     * @param value value to bind as VC_TO_DATE
     */
    public void setVC_TO_DATE(Date value) {
        ensureVariableManager().setVariableValue("VC_TO_DATE", value);
    }

    /**
     * Returns the variable value for VC_MEMBERSHIP_NO.
     * @return variable value for VC_MEMBERSHIP_NO
     */
    public String getVC_MEMBERSHIP_NO() {
        return (String) ensureVariableManager().getVariableValue("VC_MEMBERSHIP_NO");
    }

    /**
     * Sets <code>value</code> for variable VC_MEMBERSHIP_NO.
     * @param value value to bind as VC_MEMBERSHIP_NO
     */
    public void setVC_MEMBERSHIP_NO(String value) {
        ensureVariableManager().setVariableValue("VC_MEMBERSHIP_NO", value);
    }

    /**
     * Returns the variable value for VC_FROM_AGENT_CODE.
     * @return variable value for VC_FROM_AGENT_CODE
     */
    public String getVC_FROM_AGENT_CODE() {
        return (String) ensureVariableManager().getVariableValue("VC_FROM_AGENT_CODE");
    }

    /**
     * Sets <code>value</code> for variable VC_FROM_AGENT_CODE.
     * @param value value to bind as VC_FROM_AGENT_CODE
     */
    public void setVC_FROM_AGENT_CODE(String value) {
        ensureVariableManager().setVariableValue("VC_FROM_AGENT_CODE", value);
    }

    /**
     * Returns the variable value for VC_TO_AGENT_CODE.
     * @return variable value for VC_TO_AGENT_CODE
     */
    public String getVC_TO_AGENT_CODE() {
        return (String) ensureVariableManager().getVariableValue("VC_TO_AGENT_CODE");
    }

    /**
     * Sets <code>value</code> for variable VC_TO_AGENT_CODE.
     * @param value value to bind as VC_TO_AGENT_CODE
     */
    public void setVC_TO_AGENT_CODE(String value) {
        ensureVariableManager().setVariableValue("VC_TO_AGENT_CODE", value);
    }

    /**
     * Returns the variable value for VC_BRANCH_CODE.
     * @return variable value for VC_BRANCH_CODE
     */
    public String getVC_BRANCH_CODE() {
        return (String) ensureVariableManager().getVariableValue("VC_BRANCH_CODE");
    }

    /**
     * Sets <code>value</code> for variable VC_BRANCH_CODE.
     * @param value value to bind as VC_BRANCH_CODE
     */
    public void setVC_BRANCH_CODE(String value) {
        ensureVariableManager().setVariableValue("VC_BRANCH_CODE", value);
    }

    /**
     * Returns the variable value for VC_REGION_CODE.
     * @return variable value for VC_REGION_CODE
     */
    public String getVC_REGION_CODE() {
        return (String) ensureVariableManager().getVariableValue("VC_REGION_CODE");
    }

    /**
     * Sets <code>value</code> for variable VC_REGION_CODE.
     * @param value value to bind as VC_REGION_CODE
     */
    public void setVC_REGION_CODE(String value) {
        ensureVariableManager().setVariableValue("VC_REGION_CODE", value);
    }

    /**
     * Returns the variable value for VC_RANK_CODE.
     * @return variable value for VC_RANK_CODE
     */
    public String getVC_RANK_CODE() {
        return (String) ensureVariableManager().getVariableValue("VC_RANK_CODE");
    }

    /**
     * Sets <code>value</code> for variable VC_RANK_CODE.
     * @param value value to bind as VC_RANK_CODE
     */
    public void setVC_RANK_CODE(String value) {
        ensureVariableManager().setVariableValue("VC_RANK_CODE", value);
    }
    
    @Override
        public void executeQuery() {
            FacesContext fctx = FacesContext.getCurrentInstance();
            ExternalContext ectx = fctx.getExternalContext();
            HttpSession userSession = (HttpSession) ectx.getSession(false);
            Object VUserID = userSession.getAttribute("pUserId") == null ? "273" : userSession.getAttribute("pUserId");
            String SsvUserType = null;
            try {
                SsvUserType = userSession.getAttribute("SSV_UserType").toString();
            } catch (Exception e) {
                SsvUserType = "ADMIN";
            }
            if ("BO".equalsIgnoreCase(SsvUserType)) {
                this.setWhereClause("EXISTS (SELECT 1\n" + 
                "            FROM DSS_SM_USERS          AA,\n" + 
                "                 PQT_IL_LOC_HEADER     AB,\n" + 
                "                 PQT_IL_LOC_BRANCH_DTL BR\n" + 
                "           WHERE 1 = 1\n" + 
                "             AND AA.GIS_LOCATION_ID_FK = AB.IL_LOC_ID_PK\n" + 
                "             AND AB.IL_LOC_ID_PK = BR.IL_LOC_ID_FK\n" + 
                "             AND BR.BRANCH_CODE = QRSLT.BRANCH_CODE\n" + 
                "             AND AA.USER_ID_PK = " + VUserID + ") ");
            }
    //        System.out.println(getQuery());
            super.executeQuery();
        }
}

