package pqt.dss.ptrf.model.vo.common;

import oracle.jbo.ViewObject;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Mon Jan 08 17:37:44 PKT 2018
// ---------------------------------------------------------------------
public interface DssPlanTransferHeaderView extends ViewObject {
    void ptrfSearchUser();

    void setNVC_wfDocumentId(oracle.jbo.domain.Number value);
}

