package pqt.dss.ptrf.model.vo;

import javax.faces.context.ExternalContext;
import javax.faces.context.FacesContext;

import javax.servlet.http.HttpSession;

import oracle.jbo.ViewCriteria;
import oracle.jbo.ViewObject;
import oracle.jbo.domain.Date;
import oracle.jbo.domain.Number;
import oracle.jbo.server.ViewObjectImpl;

import pqt.dss.ptrf.model.vo.common.DssPlanTransferHeaderView;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Mon Jan 08 16:50:25 PKT 2018
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class DssPlanTransferHeaderViewImpl extends ViewObjectImpl implements DssPlanTransferHeaderView {
    /**
     * This is the default constructor (do not remove).
     */
    public DssPlanTransferHeaderViewImpl() {
    }

    /**
     * Returns the variable value for VC_Branch_Code.
     * @return variable value for VC_Branch_Code
     */
    public String getVC_Branch_Code() {
        return (String) ensureVariableManager().getVariableValue("VC_Branch_Code");
    }

    /**
     * Sets <code>value</code> for variable VC_Branch_Code.
     * @param value value to bind as VC_Branch_Code
     */
    public void setVC_Branch_Code(String value) {
        ensureVariableManager().setVariableValue("VC_Branch_Code", value);
    }

    /**
     * Returns the variable value for VC_Enter_Date.
     * @return variable value for VC_Enter_Date
     */
    public Date getVC_Enter_Date() {
        return (Date) ensureVariableManager().getVariableValue("VC_Enter_Date");
    }

    /**
     * Sets <code>value</code> for variable VC_Enter_Date.
     * @param value value to bind as VC_Enter_Date
     */
    public void setVC_Enter_Date(Date value) {
        ensureVariableManager().setVariableValue("VC_Enter_Date", value);
    }

    /**
     * Returns the variable value for VC_Document_No.
     * @return variable value for VC_Document_No
     */
    public String getVC_Document_No() {
        return (String) ensureVariableManager().getVariableValue("VC_Document_No");
    }

    /**
     * Sets <code>value</code> for variable VC_Document_No.
     * @param value value to bind as VC_Document_No
     */
    public void setVC_Document_No(String value) {
        ensureVariableManager().setVariableValue("VC_Document_No", value);
    }


    public void exeViewCrieteria(Number val)
                {
                    ViewObject vo = this.getViewObject();
                    ViewCriteria vc = this.getViewCriteria("NotificationViewCriteria");
                    vo.applyViewCriteria(vc);
                    vo.setNamedWhereClauseParam("NVC_wfDocumentId", val);
                    vo.executeQuery();
                    }
    /**
     * Returns the variable value for NVC_wfDocumentId.
     * @return variable value for NVC_wfDocumentId
     */
    public Number getNVC_wfDocumentId() {
        return (Number) ensureVariableManager().getVariableValue("NVC_wfDocumentId");
    }

    /**
     * Sets <code>value</code> for variable NVC_wfDocumentId.
     * @param value value to bind as NVC_wfDocumentId
     */
    public void setNVC_wfDocumentId(Number value) {
        ensureVariableManager().setVariableValue("NVC_wfDocumentId", value);
        this.exeViewCrieteria(value);
    }
    public void ptrfSearchUser()
    {
              ViewCriteria vc = this.getViewCriteria("DssPlanTransferHeaderViewCriteria");
              this.applyViewCriteria(vc);

              setWhereClause(null);
              FacesContext fctx = FacesContext.getCurrentInstance();
              ExternalContext ectx = fctx.getExternalContext();
//              HttpSession userSession = (HttpSession) ectx.getSession(false);
              HttpSession userSession = (HttpSession) ectx.getSession(false);
//              userSession.setAttribute("SSV_UserDept", 3);
//              userSession.setAttribute("pUserId",1139);
//                      userSession.setAttribute("SSV_UserType","BO");
              Object VUserID = userSession.getAttribute("pUserId") == null ? "0" : userSession.getAttribute("pUserId");
              if (userSession.getAttribute("SSV_UserType").equals("BO")) {
                  setWhereClause("((exists (select 1 FROM DSS_SM_USERS AA, PQT_IL_LOC_BRANCH_DTL BD " + " WHERE 1=1" +
                                 " AND AA.USER_ID_PK  =" + VUserID +
                                 " AND AA.GIS_LOCATION_ID_FK = BD.IL_LOC_ID_FK " +
                                 " AND BD.BRANCH_CODE = QRSLT.BRANCH_CODE_FK)))");
              }    //              setWhereClause("USER_ID_FK =" + VUserID);
              executeQuery();
          }
}

